# ./docker-compose.yml

services:
  db:
    image: postgres:17-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sapflux
    ports:
      - '5432:5432'
    # CORRECTED: This now correctly refers to the named volume defined below.
    volumes:
      - postgres_data_vol:/var/lib/postgresql/data

# CORRECTED: The named volume is defined here.
volumes:
  postgres_data_vol: