[package]
name = "sapflux-parser"
version = "0.1.0"
edition = "2024"

[dependencies]
polars = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
csv = { workspace = true }
chrono = { workspace = true }
zip = "0.6"
