[package]
name = "sapflux-bucket"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1"
aws-config = { version = "1.1.5", features = ["behavior-version-latest"] }
aws-sdk-s3 = "1.24.0"
aws-credential-types = "1.1.5"
bytes = "1.6"
thiserror = { workspace = true }
