# Daylight Saving Time transition points for US Eastern Time.
#
# 'action' can be "start" (spring forward) or "end" (fall back).
# 'ts_local' is the naive, local wall-clock time when the transition occurs.
# This format is intentionally timezone-naive to match the behavior of the
# dataloggers. The processing logic will interpret these values correctly.

[[transitions]]
action = "start"
ts_local = "2011-03-13T03:00:00"

[[transitions]]
action = "start"
ts_local = "2012-03-11T03:00:00"

[[transitions]]
action = "start"
ts_local = "2013-03-10T03:00:00"

[[transitions]]
action = "start"
ts_local = "2014-03-09T03:00:00"

[[transitions]]
action = "start"
ts_local = "2015-03-08T03:00:00"

[[transitions]]
action = "start"
ts_local = "2016-03-13T03:00:00"

[[transitions]]
action = "start"
ts_local = "2017-03-12T03:00:00"

[[transitions]]
action = "start"
ts_local = "2018-03-11T03:00:00"

[[transitions]]
action = "start"
ts_local = "2019-03-10T03:00:00"

[[transitions]]
action = "start"
ts_local = "2020-03-08T03:00:00"

[[transitions]]
action = "start"
ts_local = "2021-03-14T03:00:00"

[[transitions]]
action = "start"
ts_local = "2022-03-13T03:00:00"

[[transitions]]
action = "start"
ts_local = "2023-03-12T03:00:00"

[[transitions]]
action = "start"
ts_local = "2024-03-10T03:00:00"

[[transitions]]
action = "start"
ts_local = "2025-03-09T03:00:00"

[[transitions]]
action = "start"
ts_local = "2026-03-08T03:00:00"

[[transitions]]
action = "start"
ts_local = "2027-03-14T03:00:00"

[[transitions]]
action = "start"
ts_local = "2028-03-12T03:00:00"

[[transitions]]
action = "start"
ts_local = "2029-03-11T03:00:00"

[[transitions]]
action = "start"
ts_local = "2030-03-10T03:00:00"

[[transitions]]
action = "end"
ts_local = "2011-11-06T02:00:00"

[[transitions]]
action = "end"
ts_local = "2012-11-04T02:00:00"

[[transitions]]
action = "end"
ts_local = "2013-11-03T02:00:00"

[[transitions]]
action = "end"
ts_local = "2014-11-02T02:00:00"

[[transitions]]
action = "end"
ts_local = "2015-11-01T02:00:00"

[[transitions]]
action = "end"
ts_local = "2016-11-06T02:00:00"

[[transitions]]
action = "end"
ts_local = "2017-11-05T02:00:00"

[[transitions]]
action = "end"
ts_local = "2018-11-04T02:00:00"

[[transitions]]
action = "end"
ts_local = "2019-11-03T02:00:00"

[[transitions]]
action = "end"
ts_local = "2020-11-01T02:00:00"

[[transitions]]
action = "end"
ts_local = "2021-11-07T02:00:00"

[[transitions]]
action = "end"
ts_local = "2022-11-06T02:00:00"

[[transitions]]
action = "end"
ts_local = "2023-11-05T02:00:00"

[[transitions]]
action = "end"
ts_local = "2024-11-03T02:00:00"

[[transitions]]
action = "end"
ts_local = "2025-11-02T02:00:00"

[[transitions]]
action = "end"
ts_local = "2026-11-01T02:00:00"

[[transitions]]
action = "end"
ts_local = "2027-11-07T02:00:00"

[[transitions]]
action = "end"
ts_local = "2028-11-05T02:00:00"

[[transitions]]
action = "end"
ts_local = "2029-11-04T02:00:00"

[[transitions]]
action = "end"
ts_local = "2030-11-03T02:00:00"