[[project]]
name = "Coastal Monitoring"
description = "Sap flux monitoring across three coastal forest sites on the Delmarva peninsula."

[[project]]
name = "Stemflow Experiment"
description = "Experimental manipulation of stemflow in Liquidambar styraciflua at Monie Bay."